name: "Running tests: style, mypy, pytest"

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    name: Style, mypy, pytest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: 3.10
    - name: Install poetry
      run: pip install poetry
    - name: Install Dependencies
      run: poetry install
    - name: Check style
      run: poetry run ruff check .
    - name: Check mypy
      run: poetry run mypy .
